apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: stage-rolebinding
objects:
- apiVersion: v1
  groupNames:
  - "system:serviceaccounts:${STAGE_NAMESPACE}"
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: stage-from-builder-puller-${STAGE_NAMESPACE}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: "system:serviceaccounts:${STAGE_NAMESPACE}"
  userNames: null
parameters:
  - name: STAGE_NAMESPACE 
    displayName: Stage Namespace
    description: Stage Namespace to enable Pull Permissions from 
    required: true
