apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gitlab-builder
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: pgadmin4
    name: pgadmin4
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: pgadmin4
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    creationTimestamp: null
    name: bpgit-berlin-db
  spec:
    ports:
    - name: bpgit-berlin-db
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: bpgit-berlin-db
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The application's http port.
    creationTimestamp: null
    labels:
      application: berlin-backend-binary
    name: berlin-backend-binary
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment-config.name: berlin-backend-binary
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
